accounts/urls.py
from django.urls import path, reverse_lazy
from accounts import views
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView
, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/(?P<pk>\d+)?', views.profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', PasswordResetView.as_view(template_name='accounts/reset_password.html'
                                                      , success_url=reverse_lazy('accounts:password_reset_done')
                                                      , email_template_name='accounts/reset_password_email.html')
         , name='reset_password'),

    path('reset-password/done/'
         , PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html')
         , name='password_reset_done'),

    path('reset-password/confirm/<uidb64>/<token>/'
         , PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html'
                                            , success_url=reverse_lazy('accounts:password_reset_complete'))
         , name='password_reset_confirm'),

    path('reset-password/complete/'
         , PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html')
         , name='password_reset_complete')
]
app_name = 'accounts'

home/urls.py
from django.urls import path, reverse_lazy
from home.views import HomeView
from . import views
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, TemplateView
, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('connect/(?P<operation>.+)/(?P<pk>\d+)', views.change_friends, name='change_friends')
]
app_name = 'home'

tutorial/urls.py
from django.contrib import admin
from tutorial import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include(("accounts.urls", 'accounts'), namespace='accounts'), name='account'),
    path('home/', include(("home.urls", 'accounts'), namespace='account'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)


class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

home/forms.py
from django import forms
from home.models import Post


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta:
        model = Post
        fields = ('post',)

home/views.py
from django.views.generic import TemplateView
from home.forms import HomeForm
from django.shortcuts import render, redirect
from home.models import Post, Friend
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
        args = {'form': form, 'posts': posts, 'users': users, 'friends': friends}
        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            users = User.objects.exclude(id=request.user.id)
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()
            post.save()
            posts = Post.objects.all().order_by('-created')
            form = HomeForm()
        args = {'form': form, 'posts': posts, 'users': users, 'friends': friends}

        return render(request, self.template_name, args)


def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('home:home')

home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <div  class="col-md-8">
    <h2>Home</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.post }}
            <br>
            <button type="submit">Submit</button>
        </form>
        <h2>{{ text }}</h2>
        {% for post in posts %}
            <h1>{{ post.post }}</h1>
            <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
        {% endfor %}
        </div>
        <div class="col-md-4">
            <h2>Other People</h2>
            {% for user in users %}
            <a href="{% url 'accounts:view_profile' pk=user.pk%}">
            <h3>{{ user.username }}</h3>
            </a>
            {% if user not in friends %}
            <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
            <button type="button" class="btn btn-success">Add</button>
            </a>
            {% endif %}

            {% endfor %}

            <h2>Friends</h2>
            {% for friend in friends %}
            <a href="{% url 'accounts:view_profile' pk=user.pk%}">
            <h3>{{ friend.username }}</h3>
            </a>
            <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
            <button type="button" class="btn btn-default">Remove</button>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}