accounts/urls.py
from django.urls import path, reverse_lazy
from accounts import views
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView
, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/(?P<pk>\d+)?', views.profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', PasswordResetView.as_view(template_name='accounts/reset_password.html'
                                                      , success_url=reverse_lazy('accounts:password_reset_done')
                                                      , email_template_name='accounts/reset_password_email.html')
         , name='reset_password'),

    path('reset-password/done/'
         , PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html')
         , name='password_reset_done'),

    path('reset-password/confirm/<uidb64>/<token>/'
         , PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html'
                                            , success_url=reverse_lazy('accounts:password_reset_complete'))
         , name='password_reset_confirm'),

    path('reset-password/complete/'
         , PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html')
         , name='password_reset_complete')
]
app_name = 'accounts'

home/urls.py
from django.urls import path, reverse_lazy
from home.views import HomeView
from . import views
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, TemplateView
, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('connect/(?P<operation>.+)/(?P<pk>\d+)', views.change_friends, name='change_friends')
]
app_name = 'home'

tutorial/urls.py
from django.contrib import admin
from tutorial import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include(("accounts.urls", 'accounts'), namespace='accounts'), name='account'),
    path('home/', include(("home.urls", 'accounts'), namespace='account'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User


# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset()


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    objects = models.Manager()
    sdq = UserProfileManager()

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = {
            'email',
            'first_name',
            'last_name',
            'password'
        }

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('home:home'))
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)


def profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

    {% block head %}
    <title>Profile</title>

    {% endblock %}

    {% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>


    {% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

    {% block head %}
    <title>Profile</title>

    {% endblock %}

    {% block body %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>


    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Welcome</h1>
        <p>
            You can log in here
        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
        </div>
    {% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Logged out</h1>
        <p>
            You have logged out
        </p>
        </div>
    {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

    {% block head %}
    <title>Profile</title>

    {% endblock %}

    {% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}<p/>
    <p>First name: {{ user.first_name }}<p/>
    <p>Last name: {{ user.last_name }}<p/>
    <p>Email: {{ user.email }}<p/>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>WebSite: {{ user.userprofile.website }}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
</div>


    {% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Register</h1>

    <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Password Reset</h1>
        <p>
            Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.
        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Reset my password</button>
        </form>
        </div>
    {% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Password Reset Complete</h1>
        <p>
            
        </p>
        <a href="{% url 'accounts:login' %}">Login</a>
        </div>
    {% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Enter new password</h1>
        <p>

        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Reset password</button>
        </form>
        </div>
    {% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

    {% block body %}

    <div class="container">
        <h1>Password Reset Sent</h1>
        <p>
            We’ve emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly. If you don’t receive an email, please make sure you’ve entered the address
            you registered with, and check your spam folder.
        </p>
        </div>
    {% endblock %}

accounts/templates/accounts/reset_password_email.html
	{% load i18n %}{% autoescape off %}
	{% blocktranslate %}You're receiving this email because you requested a password reset
    for your user account at {{ site_name }}.{% endblocktranslate %}

	{% translate "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

	{% translate "Thanks for using our site!" %}

	{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

	{% endautoescape %}